version: '3.8'
services:
  db:
    image: postgres:16-bookworm@sha256:92620daddcd947f8d5ab5ba66e848702fe443d87fed30c4cea8e389fd78dfc55
    env_file:
      - ./.env.example
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-audit}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - ${SQL_PORT:-5432}
    restart: on-failure
  web:
    build: 
      context: ./
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/web_entrypoint.sh' ]
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
    restart: on-failure
  nginx:
    image: nginx:stable-bookworm@sha256:552e7481ca93ffccd046aa658dbbed22caefbc09c66fa7cd247cbb90b8a5c609
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
    restart: on-failure
  rabbitmq:
    image: rabbitmq:4.2-management@sha256:a570a0204bbbd357cd7fdac90f9f1b72f644d06dda4c49799a9452e5b9941dfc
    env_file:
      - ./.env.example
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    expose:
      - "5672"
    depends_on:
      - web
    restart: on-failure
  worker:
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/worker_entrypoint.sh' ]
    volumes:
      - .:/app
    links:
      - rabbitmq
      - web
    depends_on:
      - rabbitmq
    restart: on-failure
volumes:
  db-data:
