# Generated by Django 3.2.2 on 2021-05-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scan_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('reference', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='risk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.risk'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='default_risk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.risk'),
        ),
    ]
