# Generated by Django 3.2 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210509_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='app',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='app.application',
            ),
        ),
        migrations.AlterField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='auth.user',
            ),
        ),
    ]
