# Generated by Django 5.2 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_allow_guest_findings'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='guest_session_fingerprint',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=64,
                null=True,
            ),
        ),
    ]
