CWE = [
    (3, 'Other'),
    (20, 'Improper Input Validation'),
    (22, 'Improper Limitation of a Pathname to a Restricted Directory (\'Path Traversal\')'),
    (25, 'Execution with Unnecessary Privileges'),
    (89, 'Improper Neutralization of Special Elements used in an SQL Command (\'SQL Injection\')'),
    (95, 'Improper Neutralization of Directives in Dynamically Evaluated Code (\'Eval Injection\')'),
    (119, 'Improper Restriction of Operations within the Bounds of a Memory Buffer'),
    (200, 'Exposure of Sensitive Information to an Unauthorized Actor'),
    (250, 'Execution with Unnecessary Privileges'),
    (276, 'Incorrect Default Permissions'),
    (295, 'Improper Certificate Validation'),
    (757, 'Selection of Less-Secure Algorithm During Negotiation (\'Algorithm Downgrade\')'),
    (297, 'Improper Validation of Certificate with Host Mismatch'),
    (311, 'Missing Encryption of Sensitive Data'),
    (312, 'Cleartext Storage of Sensitive Information'),
    (327, 'Use of a Broken or Risky Cryptographic Algorithm'),
    (329, 'Not Using a Random IV with CBC Mode'),
    (330, 'Use of Insufficiently Random Values'),
    (396, 'Declaration of Catch for Generic Exception'),
    (502, 'Deserialization of Untrusted Data'),
    (530, 'Exposure of Backup File to an Unauthorized Control Sphere'),
    (532, 'Insertion of Sensitive Information into Log File'),
    (676, 'Use of Potentially Dangerous Function'),
    (749, 'Exposed Dangerous Method or Function'),
    (780, 'Use of RSA Algorithm without OAEP'),
    (789, 'Uncontrolled Memory Allocation'),
    (919, 'Weaknesses in Mobile Applications'),
    (926, 'Improper Export of Android Application Components'),
    (939, 'Improper Authorization in Handler for Custom URL Scheme'),
    (1021, 'Improper Restriction of Rendered UI Layers or Frames'),
]